spring:

  ai:
    ollama:
      base-url: http://192.168.1.19:11434
      chat:
        options:
          model: llama3

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

sketch2code:
  vision:
    model: llava
    temperature: 0.0
  code:
    model: qwen2.5-coder:3b
    temperature: 0.0
